Repository bitaxeorg/ESP-Miner, pull requests merged in 2024-09, with the labels that each got.

#318 Fix websocket logs causing device to crash #277
  main/http_server/http_server.c
Labels: bug, accepted

#334 increase overheat activation to 85C
  main/tasks/power_management_task.c
Labels: enhancement

#349 Version mask now based on stratum msg
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  components/asic/include/bm1366.h
  components/asic/include/bm1368.h
  components/asic/include/bm1370.h
  components/asic/include/bm1397.h
  components/stratum/include/utils.h
  main/global_state.h
  main/main.c
  main/tasks/create_jobs_task.c
  main/tasks/stratum_task.c
Labels: accepted

#338 Set default cpu freq to 240mhz
  sdkconfig.defaults
Labels: accepted

#353 Suggest difficulty after auth to fix ckpool issue
  main/tasks/stratum_task.c
Labels: accepted

#326 Protect against negative frequency and voltage values
  main/http_server/http_server.c
Labels: enhancement, accepted

#295 Add MAC address to API.
  main/http_server/http_server.c
Labels: enhancement

#280 minor change to ckpool quicklink detector
  main/http_server/axe-os/src/app/components/home/home.component.ts
Labels: enhancement
