Repository bitaxeorg/ESP-Miner, pull requests merged in 2024-12, with the labels that each got.

#425 Add uptime to home screen
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/pipes/date-ago.pipe.ts
Labels: enhancement, design, accepted

#539 LVGL All The Things!
  .vscode/settings.json
  components/connect/connect.c
  components/connect/include/connect.h
  main/CMakeLists.txt
  main/display.c
  main/display.h
  main/fonts.c
  main/global_state.h
  main/i2c_bitaxe.c
  main/i2c_bitaxe.h
  main/idf_component.yml
  main/input.c
  main/input.h
  main/logo.c
  main/lv_conf.h
  main/lv_font_portfolio-6x8.c
  main/main.c
  main/main.h
  main/oled.c
  main/oled.h
  main/screen.c
  main/screen.h
  main/self_test/self_test.c
  main/system.c
  main/system.h
  main/tasks/power_management_task.c
  main/tasks/user_input_task.c
  main/tasks/user_input_task.h
  readme.md
  sdkconfig.defaults
Labels: enhancement, design

#569 Adds solohash getQuickLink()
  main/http_server/axe-os/src/app/components/home/home.component.ts
Labels: design

#578 fix: Show custom values in dropdown if set
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
Labels: design, accepted

#580 Toggle auto_fan_speed without reboot
  main/tasks/power_management_task.c
Labels: enhancement, accepted

#468 Enable PSRAM
  sdkconfig.defaults
Labels: enhancement, good first issue
