Repository bitaxeorg/ESP-Miner, pull requests merged in 2024-11, with the labels that each got.

#430 Redo swarm
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
  main/http_server/axe-os/src/app/local-storage.service.spec.ts
  main/http_server/axe-os/src/app/local-storage.service.ts
  main/http_server/http_server.c
Labels: bug

#424 Fix api not handling errors properly
  main/http_server/http_server.c
Labels: enhancement, accepted

#453 fix: Change log font and add colors
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/logs/logs.component.scss
  main/http_server/axe-os/src/app/components/logs/logs.component.ts
Labels: design, accepted

#455 fix: Better restart feedback & attempt to fix CORS
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
  main/http_server/http_server.c
Labels: bug, enhancement, accepted

#457 fix: Sort swarm, dup check, auto add not overwrite, import cleanup
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
Labels: enhancement, design, accepted

#503 Fix bug when setting baudrate that can prevent the ASIC from working
  components/asic/serial.c
Labels: bug, enhancement

#450 Rejected Shares Percentage Information added
  main/http_server/axe-os/src/app/components/home/home.component.html
Labels: good first issue, design

#413 Add Recovery Image to CI
  .github/workflows/release-recovery-beta.yml
  .github/workflows/release-recovery.yml
Labels: accepted
