Repository bitaxeorg/ESP-Miner, pull requests merged in 2024-10, with the labels that each got.

#327 Increase the max number of log lines stored in browser
  main/http_server/axe-os/src/app/components/logs/logs.component.ts
Labels: accepted

#336 Add stratum fallback support
  components/stratum/include/stratum_api.h
  components/stratum/stratum_api.c
  main/Kconfig.projbuild
  main/global_state.h
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/nvs_config.h
  main/system.c
  main/tasks/asic_result_task.c
  main/tasks/stratum_task.c
  main/tasks/stratum_task.h
Labels: enhancement, accepted

#379 fix #374 Issue 1 : Fallback Stratum Password
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/layout/app.menu.component.html
  main/http_server/axe-os/src/app/layout/styles/layout/_menu.scss
Labels: bug, design, accepted

#364 Add overheat button and change loading service
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/services/loading.service.ts
Labels: enhancement, design

#402 Fix bad www.bin loads
  main/i2c_bitaxe.c
  main/i2c_bitaxe.h
Labels: bug

#416 Add OLED Bitaxe logo screen
  main/oled.c
  main/oled.h
  main/system.c
Labels: design, accepted

#433 Chart enhance
  main/http_server/axe-os/src/app/components/home/home.component.ts
Labels: design
