Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-09, with the labels that each got.

#1213 Block found screen sometimes doesn't show
  main/screen.c
Labels: bug

#1200 Show block header, scriptsig and network difficulty
  components/stratum/include/utils.h
  components/stratum/utils.c
  main/global_state.h
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.scss
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
  main/screen.c
  main/system.c
  main/tasks/stratum_task.c
Labels: design, accepted

#1214 Add degree symbol on display
  main/lv_font_portfolio-6x8.c
  main/screen.c
Labels: design

#1223 Rearrange swarm layout
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
Labels: design

#1238 Add space before dBm
  main/http_server/axe-os/src/app/components/system/system.component.ts
  main/http_server/axe-os/src/app/services/dialog.service.ts
Labels: design

#1145 Introduce tools/upload2device.py
  tools/upload2device.py
Labels: enhancement

#1215 Switch to latest stable verion of ESP IDF 5.5.1
  .devcontainer/Dockerfile
  .github/workflows/build.yml
  .github/workflows/release-beta.yml
  .github/workflows/release-factory-beta.yml
  .github/workflows/release-factory.yml
  .github/workflows/release.yml
  .github/workflows/unittest.yml
Labels: enhancement

#1232 Fix color representation for Nerdaxe devices
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
Labels: design

#1160 Replace deprecated HttpClientModule
  main/http_server/axe-os/src/app/app.module.ts
Labels: cleanup
