Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-07, with the labels that each got.

#1126 Remove fallback code for 7xx board versions
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
Labels: cleanup

#1102 Common difficulty mask function
  components/asic/asic.c
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  components/asic/common.c
  components/asic/include/asic.h
  components/asic/include/bm1366.h
  components/asic/include/bm1368.h
  components/asic/include/bm1370.h
  components/asic/include/bm1397.h
  components/asic/include/common.h
  main/power/TPS546.c
  main/power/TPS546.h
  main/power/vcore.c
  main/power/vcore.h
  main/self_test/self_test.c
  main/system.c
  main/tasks/power_management_task.c
  main/thermal/thermal.c
  main/thermal/thermal.h
Labels: cleanup

#1042 Add Privacy Warning to Release Check
  main/http_server/axe-os/src/app/components/modal/modal.component.html
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
  main/http_server/axe-os/src/app/components/update/update.component.html
  main/http_server/axe-os/src/app/components/update/update.component.ts
  main/http_server/axe-os/src/styles.scss
Labels: enhancement, design

#1038 Remove unused PrimeNG icons
  main/http_server/axe-os/src/app/layout/styles/modules/primeng.min.css
  main/http_server/axe-os/src/styles.scss
Labels: cleanup

#1059 Configure min fan speed percentage
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
  main/nvs_config.h
  main/tasks/power_management_task.c
Labels: enhancement

#1163 fix: bump up idf 5.5
  .devcontainer/Dockerfile
  .github/workflows/build.yml
  .github/workflows/release-beta.yml
  .github/workflows/release-factory-beta.yml
  .github/workflows/release-factory.yml
  .github/workflows/release.yml
  .github/workflows/unittest.yml
Labels: cleanup

#1149 Show/Hide pool advanced options
  main/http_server/axe-os/src/app/components/pool/pool.component.html
  main/http_server/axe-os/src/app/components/pool/pool.component.ts
Labels: design
