Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-04, with the labels that each got.

#849 fix: spelling error fix
  components/asic/bm1397.c
  components/asic/include/bm1397.h
  components/asic/serial.c
Labels: accepted

#835 Make "Latest Release" into a link for the changelog
  main/http_server/axe-os/src/app/components/settings/settings.component.html
Labels: design, accepted

#525 Screensaver timeout
  main/display.c
  main/display.h
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/nvs_config.c
  main/nvs_config.h
  main/screen.c
Labels: enhancement, good first issue

#834 Update gitignore, simplify layout, fix refresh button UI, unify headlines/margins, improve modal responsiveness and theme color selection
  .gitignore
  main/http_server/axe-os/src/app/components/design/design-component.scss
  main/http_server/axe-os/src/app/components/design/theme-config.component.ts
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/pool/pool.component.html
  main/http_server/axe-os/src/app/components/settings/settings.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.scss
  main/http_server/axe-os/src/app/layout/styles/layout/_content.scss
  main/http_server/axe-os/src/app/layout/styles/layout/_utils.scss
Labels: design, accepted

#854 Initial page load causes multiple inconsistent GET responses
  main/http_server/axe-os/src/app/components/design/theme-config.component.ts
  main/http_server/axe-os/src/app/components/home/home.component.ts
  main/http_server/axe-os/src/app/layout/service/app.layout.service.ts
  main/http_server/axe-os/src/app/services/theme.service.ts
  main/http_server/theme_api.c
  main/nvs_config.h
Labels: enhancement, design

#862 Api rework asic
  main/CMakeLists.txt
  main/http_server/axe-os/api/system/asic_settings.c
  main/http_server/axe-os/api/system/asic_settings.h
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
Labels: enhancement
