Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-08, with the labels that each got.

#1172 feat: test both temps gt
  main/device_config.h
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
  main/tasks/power_management_task.c
  main/tasks/power_management_task.h
  main/thermal/EMC2103.c
  main/thermal/EMC2103.h
  main/thermal/thermal.c
  main/thermal/thermal.h
Labels: enhancement, design

#1134 Add tooltips for suggest difficulty and extranonce subscribe pool fields
  main/http_server/axe-os/src/app/components/pool/pool.component.html
Labels: enhancement, design

#1168 Extranonce 2 variable length
  .gitignore
  components/stratum/include/mining.h
  components/stratum/mining.c
  components/stratum/stratum_api.c
  main/tasks/create_jobs_task.c
  main/tasks/stratum_task.c
Labels: cleanup

#1170 Add Pool Difficulty to Dashboard
  main/http_server/axe-os/src/app/components/home/home.component.html
Labels: enhancement

#1004 Generate sdkconfig.defaults
  sdkconfig.defaults
Labels: cleanup

#1162 Fix statistics deactivation without restart
  main/tasks/statistics_task.c
  main/tasks/statistics_task.h
Labels: bug, accepted
