Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-06, with the labels that each got.

#1000 Improve Logs Fullscreen
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/logs/logs.component.scss
  main/http_server/axe-os/src/app/components/logs/logs.component.ts
Labels: bug

#951 Fix chart tooltip reset on every data change
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.ts
Labels: bug

#884 Add clear button and filter for realtime logs
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/logs/logs.component.ts
Labels: enhancement

#983 Uniform icon only buttons
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/logs/logs.component.scss
  main/http_server/axe-os/src/app/components/network-edit/network.edit.component.html
  main/http_server/axe-os/src/styles.scss
Labels: cleanup

#977 Uniform logging tags
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  components/asic/frequency_transition_bmXX.c
  components/dns_server/dns_server.c
  main/adc.c
  main/http_server/axe-os/api/system/asic_settings.c
  main/power/vcore.c
  main/system.c
  main/tasks/asic_task.c
Labels: cleanup

#954 Set FreeRTOS frequency to 1000Hz and enable bootloader compiler optimization
  sdkconfig.defaults
Labels: enhancement

#956 Add Parasite pool to Pool Quick Links
  main/http_server/axe-os/src/app/services/quicklink.service.ts
Labels: enhancement

#948 Add sorting to all swarm table columns
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
Labels: enhancement

#1020 LVGL upstream bug
  main/idf_component.yml
Labels: bug

#996 Add browser tab title
  main/http_server/axe-os/src/app/app-routing.module.ts
  main/http_server/axe-os/src/app/components/home/home.component.ts
Labels: enhancement

#992 Add Ultra 207 support
  .github/workflows/release-factory-beta.yml
  .github/workflows/release-factory.yml
  config-207.cvs
  main/device_config.h
Labels: enhancement, critical

#1019 Add signal strength indicator to screen
  main/screen.c
Labels: enhancement

#1023 Wait after socket creation
  main/tasks/stratum_task.c
Labels: bug

#966 Add board family to API
  main/http_server/axe-os/api/system/asic_settings.c
  main/http_server/openapi.yaml
Labels: enhancement

#972 api returns a JSON error for unhandled requests
  main/http_server/http_server.c
Labels: enhancement

#978 Init ASIC frequency in power_management_task
  main/main.c
  main/tasks/power_management_task.c
  main/tasks/power_management_task.h
Labels: cleanup

#979 Self_test check and Wi-Fi code moved to modules
  components/connect/connect.c
  components/connect/include/connect.h
  main/main.c
  main/main.h
  main/self_test/self_test.c
  main/self_test/self_test.h
Labels: cleanup

#982 Refactoring Power & Heat cards
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.scss
  main/http_server/axe-os/src/styles.scss
Labels: cleanup

#984 Fix duplicated help messages in Kconfig.projbuild
  main/Kconfig.projbuild
Labels: documentation

#1010 Remove duplicate fonts on production build
  main/http_server/axe-os/src/styles.scss
Labels: cleanup

#1021 Minor update to NPM packages
  main/http_server/axe-os/package-lock.json
  main/http_server/axe-os/package.json
Labels: cleanup

#1026 Rethinking Navigation
  main/http_server/axe-os/src/app/app-routing.module.ts
  main/http_server/axe-os/src/app/app.module.ts
  main/http_server/axe-os/src/app/components/design/design.component.html
  main/http_server/axe-os/src/app/components/design/theme-config.component.ts
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/settings/settings.component.html
  main/http_server/axe-os/src/app/components/settings/settings.component.scss
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
  main/http_server/axe-os/src/app/components/system/system.component.html
  main/http_server/axe-os/src/app/components/system/system.component.spec.ts
  main/http_server/axe-os/src/app/components/system/system.component.ts
  main/http_server/axe-os/src/app/components/update/update.component.html
  main/http_server/axe-os/src/app/components/update/update.component.scss
  main/http_server/axe-os/src/app/components/update/update.component.spec.ts
  main/http_server/axe-os/src/app/components/update/update.component.ts
  main/http_server/axe-os/src/app/layout/app.menu.component.ts
  main/http_server/axe-os/src/app/layout/app.menuitem.component.ts
Labels: enhancement

#1041 FUP #1005: Use Modal Component for Release Notes
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
  main/http_server/axe-os/src/app/components/update/update.component.html
  main/http_server/axe-os/src/app/components/update/update.component.ts
Labels: cleanup

#1050 Refactored settings component
  main/http_server/axe-os/src/app/components/settings/settings.component.scss
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
Labels: cleanup

#1049 Refresh Logs Page
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/logs/logs.component.scss
  main/http_server/axe-os/src/app/components/logs/logs.component.ts
  main/http_server/axe-os/src/app/layout/styles/theme/themes/vela/_variables.scss
  main/http_server/axe-os/src/app/layout/styles/theme/themes/vela/bitaxe/_variables.scss
  main/http_server/axe-os/src/styles.scss
Labels: design

#1027 Fix Angular build warnings
  main/http_server/axe-os/angular.json
Labels: cleanup

#1033 Remove Knob Module
  main/http_server/axe-os/src/app/prime-ng.module.ts
Labels: cleanup

#1022 SH1107 (64x128) display support completed
  config-102.cvs
  config-201.cvs
  config-202.cvs
  config-203.cvs
  config-204.cvs
  config-205.cvs
  config-207.cvs
  config-401.cvs
  config-402.cvs
  config-403.cvs
  config-601.cvs
  config-602.cvs
  config-800x.cvs
  config-custom.cvs
  config.cvs.example
  main/CMakeLists.txt
  main/display.c
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
  main/idf_component.yml
  main/lv_conf.h
  main/nvs_config.h
  main/screen.c
  sdkconfig.defaults
Labels: enhancement, api change

#1030 Simplify Wi-Fi screen
  main/screen.c
Labels: cleanup

#1066 Introduction Loading Animation
  main/http_server/axe-os/src/app/app.component.html
  main/http_server/axe-os/src/app/app.module.ts
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.ts
  main/http_server/axe-os/src/app/components/loading/loading.component.html
  main/http_server/axe-os/src/app/components/loading/loading.component.scss
  main/http_server/axe-os/src/app/components/system/system.component.html
  main/http_server/axe-os/src/app/components/system/system.component.ts
  main/http_server/axe-os/src/app/layout/app.layout.component.html
  main/http_server/axe-os/src/app/layout/app.layout.module.ts
  main/http_server/axe-os/src/app/layout/styles/layout/_menu.scss
  main/http_server/axe-os/src/app/layout/styles/layout/_responsive.scss
  main/http_server/axe-os/src/app/layout/styles/theme/themes/vela/_variables.scss
Labels: design

#1006 Add AxeOS version and mismatched version warning
  doc/unit_testing.md
  main/http_server/axe-os/generate-version.js
  main/http_server/axe-os/package.json
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/system/system.component.html
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
Labels: enhancement

#1073 Fix selected accent color after page reload
  main/http_server/axe-os/src/app/components/design/theme-config.component.ts
Labels: bug, design

#1089 Swarm should handle devices without asic endpoint
  main/http_server/axe-os/api/system/asic_settings.c
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
  main/http_server/axe-os/src/app/components/system/system.component.html
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemASIC.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
Labels: enhancement, api change
