Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-01, with the labels that each got.

#478 Streamline create_jobs_task
  main/tasks/create_jobs_task.c
Labels: help wanted, accepted

#566 Configure GPIO in Kconfig
  .vscode/settings.json
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  main/CMakeLists.txt
  main/Kconfig.projbuild
  main/i2c_bitaxe.c
  main/input.c
  main/led_controller.c
  main/led_controller.h
  main/self_test/self_test.c
  main/system.c
  main/tasks/power_management_task.c
Labels: enhancement, accepted

#546 test: fix failing unit test for large stratum id
  components/stratum/test/test_stratum_json.c
Labels: unit_tests

#548 test: add boundary check for implicit response method
  components/stratum/test/test_stratum_json.c
Labels: unit_tests

#552 Improve i2c error logging
  main/DS4432U.c
  main/EMC2101.c
  main/INA260.c
  main/TMP1075.c
  main/TPS546.c
  main/i2c_bitaxe.c
  main/i2c_bitaxe.h
Labels: enhancement

#612 Fix logs not rendering properly in AxeOS
  sdkconfig.defaults
Labels: bug

#629 typo: small typo fix
  main/main.c
Labels: good first issue, accepted

#608 test: fix stratum alternative error unit test
  components/stratum/test/test_stratum_json.c
Labels: unit_tests

#637 CSRF
  main/http_server/http_server.c
Labels: bug, enhancement, accepted, swarm, critical

#543 Keep old pool config synchronized until reboot
  main/global_state.h
  main/system.c
  main/tasks/asic_result_task.c
  main/tasks/stratum_task.c
Labels: enhancement

#647 fix: Color swarm ips by model or count
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
Labels: design, accepted

#646 fix: Show IP of bitaxe you are restarting on swarm
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/swarm/swarm.component.ts
Labels: design, accepted

#649 refactor: make recovery page an embedded file
  main/CMakeLists.txt
  main/http_server/http_server.c
  main/http_server/recovery_page.h
  main/http_server/recovery_page.html
Labels: enhancement

#675 Menu rework, adding menu Design
  main/http_server/axe-os/src/app/app-routing.module.ts
  main/http_server/axe-os/src/app/app.module.ts
  main/http_server/axe-os/src/app/components/design/design.component.html
  main/http_server/axe-os/src/app/components/design/design.component.ts
  main/http_server/axe-os/src/app/components/design/theme-config.component.ts
  main/http_server/axe-os/src/app/components/settings/settings.component.html
  main/http_server/axe-os/src/app/layout/app.menu.component.ts
Labels: design

#676 Pool rework menu
  main/http_server/axe-os/src/app/app-routing.module.ts
  main/http_server/axe-os/src/app/app.module.ts
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/pool/pool.component.html
  main/http_server/axe-os/src/app/components/pool/pool.component.scss
  main/http_server/axe-os/src/app/components/pool/pool.component.ts
  main/http_server/axe-os/src/app/layout/app.menu.component.ts
Labels: design, accepted

#660 add support for extranonce2_len<4
  components/stratum/mining.c
Labels: bug, enhancement

#480 Reduce invalid job found log from error to warning
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  main/tasks/asic_result_task.c
Labels: enhancement, accepted
