Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-05, with the labels that each got.

#603 feature: add expected hashrate to api
  main/http_server/http_server.c
Labels: enhancement

#906 Fix scientific notation in best session diff
  main/system.c
Labels: bug

#859 Clean up NVS Wi-Fi credentials code
  components/connect/connect.c
  components/connect/include/connect.h
  main/main.c
  main/nvs_config.c
  main/nvs_device.c
  main/nvs_device.h
Labels: accepted

#875 emc2101-fix and emc2103
  main/thermal/EMC2101.c
  main/thermal/EMC2101.h
  main/thermal/EMC2103.c
  main/thermal/EMC2103.h
Labels: enhancement

#923 Pools Visual Separation
  main/http_server/axe-os/src/app/components/pool/pool.component.html
Labels: design

#910 Message update with ref to new firmware release.
  main/http_server/axe-os/src/app/components/settings/settings.component.html
Labels: design

#924 Add Project Favicon
  main/http_server/axe-os/src/favicon.ico
Labels: design

#934 Add support for multiple displays
  main/device_config.h
  main/display.c
  main/display.h
  main/global_state.h
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/idf_component.yml
  main/nvs_config.h
  main/self_test/self_test.c
  main/system.c
Labels: enhancement, design

#937 Ssd1309 extra screen
  main/display.c
  main/screen.c
Labels: enhancement

#898 Statistics task for previous chart data
  main/CMakeLists.txt
  main/global_state.h
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/axe-os/src/models/ISystemStatistics.ts
  main/http_server/http_server.c
  main/http_server/openapi.yaml
  main/main.c
  main/nvs_config.h
  main/tasks/statistics_task.c
  main/tasks/statistics_task.h
Labels: enhancement, design

#938 SH1107 improvements, incomplete
  main/display.c
  main/display.h
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/i2c_bitaxe.h
Labels: enhancement

#930 Add amount of active devices to the swarm page
  main/http_server/axe-os/src/app/components/swarm/swarm.component.html
Labels: design, accepted

#929 Remember menu toggle state
  main/http_server/axe-os/src/app/layout/service/app.layout.service.ts
Labels: design, accepted
