Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-02, with the labels that each got.

#678 Update angular to 18
  main/http_server/axe-os/package-lock.json
  main/http_server/axe-os/package.json
Labels: accepted

#679 SSID WiFi lookup
  components/connect/connect.c
  components/connect/include/connect.h
  main/http_server/axe-os/src/app/app.module.ts
  main/http_server/axe-os/src/app/components/network-edit/network.edit.component.html
  main/http_server/axe-os/src/app/components/network-edit/network.edit.component.ts
  main/http_server/axe-os/src/app/services/dialog.service.ts
  main/http_server/http_server.c
Labels: enhancement

#682 fix: adjust wifi setup text speed
  main/screen.c
Labels: enhancement, design, accepted

#690 Wifi scan fix
  components/connect/connect.c
  components/connect/include/connect.h
  main/http_server/http_server.c
  main/tasks/stratum_task.c
Labels: bug, accepted

#693 Improved pool fallback code
  components/stratum/include/stratum_api.h
  components/stratum/stratum_api.c
  main/global_state.h
  main/tasks/asic_result_task.c
  main/tasks/stratum_task.c
Labels: enhancement

#685 More Wi-Fi spelling fixes
  main/http_server/axe-os/src/app/components/logs/logs.component.html
  main/http_server/axe-os/src/app/components/network-edit/network.edit.component.html
Labels: design

#624 Init AxeOS AP mode
  main/http_server/axe-os/src/app/app-routing.module.ts
  main/http_server/axe-os/src/app/guards/ap-mode.guard.ts
  main/http_server/axe-os/src/app/layout/app.layout.component.html
  main/http_server/axe-os/src/app/layout/app.layout.component.ts
  main/http_server/axe-os/src/app/layout/app.topbar.component.html
  main/http_server/axe-os/src/app/layout/app.topbar.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
Labels: enhancement

#706 Disable softap even if we don't have a valid model
  main/main.c
Labels: enhancement, accepted

#643 fix: Move avg hash to card & add eff avg
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.ts
Labels: design

#712 add Pro mode button
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
Labels: enhancement, design

#714 feat: unlock OC
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/app/components/settings/settings.component.ts
Labels: enhancement

#720 feat: update readme
  readme.md
Labels: documentation

#664 Show firmware updates on the display
  main/global_state.h
  main/http_server/http_server.c
  main/screen.c
  main/screen.h
Labels: design
