Repository bitaxeorg/ESP-Miner, pull requests merged in 2025-03, with the labels that each got.

#746 Show share reject reasons
  components/stratum/stratum_api.c
  main/global_state.h
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/system.c
  main/system.h
  main/tasks/stratum_task.c
Labels: enhancement

#749 fix: current not exposed to api
  main/http_server/http_server.c
  main/power/power.c
  main/power/power.h
Labels: bug, enhancement

#743 Remove unit test workaround for qemu
  components/stratum/utils.c
  test-ci/sdkconfig.defaults
Labels: accepted

#717 Refactor Stratum code for Seamless Failover
  components/asic/asic.c
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  components/asic/include/asic.h
  components/asic/include/bm1366.h
  components/asic/include/bm1368.h
  components/asic/include/bm1370.h
  components/asic/include/bm1397.h
  components/stratum/include/mining.h
  components/stratum/include/stratum_api.h
  components/stratum/mining.c
  components/stratum/stratum_api.c
  components/stratum/test/test_stratum_json.c
  main/global_state.h
  main/http_server/http_server.c
  main/main.c
  main/self_test/self_test.c
  main/tasks/asic_result_task.c
  main/tasks/asic_task.c
  main/tasks/create_jobs_task.c
  main/tasks/stratum_task.c
  main/tasks/stratum_task.h
Labels: enhancement

#747 feat: frequency transition
  components/asic/CMakeLists.txt
  components/asic/asic.c
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/frequency_transition_bmXX.c
  components/asic/include/asic.h
  components/asic/include/bm1366.h
  components/asic/include/bm1368.h
  components/asic/include/bm1370.h
  components/asic/include/frequency_transition_bmXX.h
  main/tasks/power_management_task.c
Labels: enhancement

#745 Verify CHIP_ID response
  components/asic/asic.c
  components/asic/bm1366.c
  components/asic/bm1368.c
  components/asic/bm1370.c
  components/asic/bm1397.c
  components/asic/common.c
  components/asic/crc.c
  components/asic/include/asic.h
  components/asic/include/bm1366.h
  components/asic/include/bm1368.h
  components/asic/include/bm1370.h
  components/asic/include/bm1397.h
  components/asic/include/common.h
  components/asic/include/serial.h
  main/self_test/self_test.c
  main/tasks/asic_result_task.c
Labels: enhancement

#770 Overclock url params
  main/http_server/axe-os/src/app/components/edit/edit.component.html
  main/http_server/axe-os/src/app/components/edit/edit.component.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/nvs_config.h
Labels: enhancement

#771 fix: swap update www and esp-miner
  main/http_server/axe-os/src/app/components/settings/settings.component.html
Labels: design

#769 ensure timeout in self test
  main/self_test/self_test.c
Labels: bug, enhancement

#735 Add whitepaper
  main/http_server/axe-os/angular.json
  main/http_server/axe-os/src/app/layout/app.menu.component.ts
  main/http_server/axe-os/src/bitcoin.pdf
  main/http_server/http_server.c
Labels: documentation, design

#739 Expose Wifi RSSI to API endpoint
  components/connect/connect.c
  components/connect/include/connect.h
  main/http_server/http_server.c
Labels: enhancement

#793 Max power gauges
  main/http_server/axe-os/src/app/components/home/home.component.html
  main/http_server/axe-os/src/app/components/home/home.component.ts
  main/http_server/axe-os/src/app/services/system.service.ts
  main/http_server/axe-os/src/models/ISystemInfo.ts
  main/http_server/http_server.c
  main/power/power.c
  main/power/power.h
Labels: enhancement, design

#777 Add asic failure status screen
  components/asic/asic.c
  main/global_state.h
  main/main.c
  main/nvs_device.c
  main/screen.c
  main/screen.h
Labels: enhancement

#763 Added nodejs and npm v22 installation
  .devcontainer/Dockerfile
Labels: enhancement
